// This file was generated by a custom prisma generator, do not edit manually.
export const UserRole = {
  ADMIN: "ADMIN",
  INSTRUCTOR: "INSTRUCTOR",
  PARTICIPANT: "PARTICIPANT",
} as const;

export type UserRole = (typeof UserRole)[keyof typeof UserRole];

export const PaymentMethod = {
  CREDIT_CARD: "CREDIT_CARD",
  DEBIT_CARD: "DEBIT_CARD",
  CASH: "CASH",
} as const;

export type PaymentMethod = (typeof PaymentMethod)[keyof typeof PaymentMethod];

export const WorkshopType = {
  PAID: "PAID",
  FREE: "FREE",
} as const;

export type WorkshopType = (typeof WorkshopType)[keyof typeof WorkshopType];

export const TestStatus = {
  PENDING: "PENDING",
  COMPLETED: "COMPLETED",
} as const;

export type TestStatus = (typeof TestStatus)[keyof typeof TestStatus];
